# Generated by Django 3.2.7 on 2021-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(through='gradebook.Gradebook', to='gradebook.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(through='gradebook.Gradebook', to='gradebook.Course'),
        ),
    ]
