# Generated by Django 3.2.7 on 2021-09-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_auto_20210921_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
